name: AntiSpamBot
main: com.zeroBzeroT.AntiSpamBot
version: 1.2.9
api-version: 1.12
author: bierdosenhalter
description: No chat until move + Check for spam
loadbefore: [ChatCo]
commands:
  movereload:
    description: Reloading plugin
    usage: /<command>
permissions:
  move.bypass:
    description: Allows you to bypass the Not-Moved-Filter
    default: false
  move.reload:
    description: Allows you to reload the NoChatUntilMove plugin
    default: false
