name: ${project.name}
main: org.zeroBzeroT.antispam.AntiSpam
version: ${project.version}
author: bierdosenhalter
description: ${project.description}
loadbefore: [ ChatCo ]
commands:
  movereload:
    description: Reloading plugin
    usage: /<command>
  showspam:
    description: shows the last spam messages
  showmessages:
    description: shows the last sanitized messages
permissions:
  move.bypass:
    description: Allows you to bypass the Not-Moved-Filter
    default: false
  move.reload:
    description: Allows you to reload the NoChatUntilMove plugin
    default: false
